# T & T LAB-03

## Name : Sudip Chakrabarty
## Roll    : 21053329
## Section : CSE-34
## Date : 10.02.24

 ### Experiment-11: 
 Create NumPy arrays with different methods (lists, zeros, ones, arange).

 Perform mathematical operations on NumPy arrays (addition, subtraction, multiplication,
 division).

 Practice indexing and slicing NumPy arrays.

 UseNumPyfunctions for basic statistical analysis like mean,median and mode.

 Experiment with reshaping and transposing NumPy arrays

In [1]:
import numpy as np
import pandas as pd

In [23]:
#Using List
list1 = [1,2,3,4,5]
list_np = np.array(list1)
print(list1)

[1, 2, 3, 4, 5]


In [24]:
#Using Zeros
zero = np.zeros((3,5))
print(zero)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [25]:
# Using ones
ones_array = np.ones((2, 4))
print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [28]:
#Using Arrange
arrange = np.arange(0,20,3)
arrange

array([ 0,  3,  6,  9, 12, 15, 18])

In [32]:
a1 = np.array([[1,2,3,4],
             [7,8,9,10]])

a2 = np.array([[10,9,8,7],
             [4,3,2,1]])
#Addition
sum1 = a1+a2
sum1

array([[11, 11, 11, 11],
       [11, 11, 11, 11]])

In [34]:
#Subtracation
sub1 = a1-a2
sub1

array([[-9, -7, -5, -3],
       [ 3,  5,  7,  9]])

In [37]:
#Multiplication
mul1 = a1*a2
mul1

array([[10, 18, 24, 28],
       [28, 24, 18, 10]])

In [38]:
#Division
div1 = a1/a2
div1

array([[ 0.1       ,  0.22222222,  0.375     ,  0.57142857],
       [ 1.75      ,  2.66666667,  4.5       , 10.        ]])

In [39]:
my_array = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Accessing
print("Element at (0, 0):", my_array[0, 0])
print("Element at (1, 2):", my_array[1, 2])

# Slicing rows and columns
print("\nFirst Row:", my_array[0])
print("Second Column:", my_array[:, 1])

# Slicing subarrays
print("\nSubarray [0:2, 1:3]:")
print(my_array[0:2, 1:3])  # Rows 0 to 1, Columns 1 to 2

# Modifying elements using indexing
my_array[1, 1] = 10
print("\nModified array:")
print(my_array)


Element at (0, 0): 1
Element at (1, 2): 6

First Row: [1 2 3]
Second Column: [2 5 8]

Subarray [0:2, 1:3]:
[[2 3]
 [5 6]]

Modified array:
[[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]]


In [42]:
sample_array = np.array([1, 2, 2, 3, 4, 4, 4, 5, 6, 7, 8, 9])

# Mean
mean_value = np.mean(sample_array)
print("Mean:", mean_value)

# Median
median_value = np.median(sample_array)
print("Median:", median_value)


from scipy import stats as st
 
# applying mode operation on array and 
# printing result
print(st.mode(sample_array))

Mean: 4.583333333333333
Median: 4.0
ModeResult(mode=4, count=3)


In [45]:
# Experimenting with reshaping and transposing
original_array = np.array([[1, 2, 3],
                           [4, 5, 6]])

# Reshaping
reshaped_array = original_array.reshape(3, 2)
print("\nReshaped Array:")
print(reshaped_array)

# Transposing
transposed_array = original_array.T
print("\nTransposed Array:")
print(transposed_array)



Reshaped Array:
[[1 2]
 [3 4]
 [5 6]]

Transposed Array:
[[1 4]
 [2 5]
 [3 6]]


### Experiment-12:
Matrix Operations

Perform various matrix operations using NumPy, such as matrix multiplication, inversion, and decomposition.

Create two random matrices using NumPy.
Perform matrix multiplication using NumPy's numpy.dot() function.
Create a random square matrix.
Invert the matrix using NumPy's numpy.linalg.inv() function.
Verify the inversion by multiplying the original matrix with its inverse.
Create a random square matrix.
Perform LU decomposition using NumPy's numpy.linalg.lu() function.
Reconstruct the original matrix from the LU factors.

In [64]:
import numpy as np

# Create two random matrices
matrix1 = (np.random.rand(3, 3) * 10).astype(int)
matrix2 = (np.random.rand(3, 3) * 10).astype(int)
print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)

# Matrix multiplication
matrix_mul = np.dot(matrix1, matrix2)
print("\nMatrix Multiplication:")
print(matrix_mul)

# Create a random square matrix
square_matrix = (np.random.rand(3, 3) * 10).astype(int)
print("\nSquare Matrix:")
print(square_matrix)

# Invert the matrix
inverse_matrix = np.linalg.inv(square_matrix)
print("\nInverted Matrix:")
print(inverse_matrix)

# Verify the inversion
identity_matrix = np.dot(square_matrix, inverse_matrix)
print("\nIdentity Matrix :")
print(identity_matrix)


Matrix 1:
[[5 0 2]
 [5 2 5]
 [1 7 1]]

Matrix 2:
[[7 2 9]
 [1 9 0]
 [4 7 1]]

Matrix Multiplication:
[[43 24 47]
 [57 63 50]
 [18 72 10]]

Square Matrix:
[[9 8 2]
 [8 7 9]
 [7 8 2]]

Inverted Matrix:
[[ 0.5         0.         -0.5       ]
 [-0.40517241 -0.03448276  0.56034483]
 [-0.12931034  0.13793103  0.00862069]]

Identity Matrix :
[[ 1.00000000e+00  0.00000000e+00 -4.37150316e-16]
 [ 1.11022302e-16  1.00000000e+00 -4.12864187e-16]
 [ 2.22044605e-16  0.00000000e+00  1.00000000e+00]]


In [73]:
from scipy.linalg import lu

size = 3
random_matrix = (np.random.rand(size,size)*10).astype(int)
print("Original Matrix:")
print(random_matrix)

lu_factorization = lu(random_matrix)
pivoted_lu = lu_factorization[0]

# Reconstruct
reconstructed_matrix = np.dot(lu_factorization[0], lu_factorization[1])
print("\nReconstructed Matrix from LU factors:")
print(reconstructed_matrix)

Original Matrix:
[[5 2 4]
 [0 2 2]
 [2 7 6]]

Reconstructed Matrix from LU factors:
[[1.         0.         0.        ]
 [0.         0.32258065 1.        ]
 [0.4        1.         0.        ]]


### END